" Enable filetype detection and plugins for automatic indentation
filetype indent plugin on

" Specific settings for YAML files
setlocal ts=2 sts=2 sw=2 expandtab
setlocal autoindent
setlocal smartindent

" Optional: Enable line numbers and cursor highlighting for better navigation
setlocal number
setlocal cursorline
setlocal cursorcolumn

" Optional: Indent guides (requires a plugin like indentLine)
let g:indentLine_char = '⦙'

" Optional: Folding based on indentation (can use built-in or a plugin like vim-yaml-folds)
" autocmd FileType yaml setlocal foldmethod=indent

" Highlight extra white space
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Turn on line numbers
set number

" Make paste behave correctly
set paste
