---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openweb-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - noatime
    - vers=4
  nfs:
    path: "/export/openweb/pvc"
    server: "192.168.2.2"
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openweb-nfs-pvc
  namespace: openweb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi