apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  type: NodePort
  ports:
    - name: nginx-service
      port: 80
      protocol: TCP
      targetPort: http-web-svc
      nodePort: 30080
