apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
          name: http-web-svc
          protocol: TCP 
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
    - name: busybox
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args: ["sleep 1000"]
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
