apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-storage
  name: nginx-storage
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-storage
  type: NodePort