apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:latest
          name: mealie
          env:
            - name: OPENAI_API_KEY
              value: "${OPENAI_API_KEY}"
            - name: BASE_URL
              value: "https://mealie.washco-web.com"
          volumeMounts:
            - name: mealie-nfs-pv
              mountPath: /app/data
          ports:
            - containerPort: 9000
      volumes:
        - name: mealie-nfs-pv
          persistentVolumeClaim:
            claimName: mealie-nfs-pvc
      

