apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  selector:
    app: mealy
  type: NodePort
  ports:
    - name: mealy-service
      port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 309000
