apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  selector:
    app: mealie
  type: NodePort
  ports:
    - name: mealie-service
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30900
