apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: mealie
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-data
  namespace: mealie
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/data" # Path on the node's filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubeworker0
          - kubeworker1
          - kubeworker2
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-storage"
  volumeName: mealie-data
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi