apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 77.12.0
    chart: kube-prometheus-stack-77.12.0
    heritage: Helm
    release: prometheus-stack
    self-monitor: "true"
  name: prometheus-node-port-service
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-stack-kube-prom-prometheus
  type: NodePort
  ports:
  - name: port-1
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30600
  - name: port-2
    port: 8080
    protocol: TCP
    targetPort: 9090
    nodePort: 30601
